# Generated by Django 4.0.5 on 2022-06-23 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_diagnosed', models.TextField(max_length=100)),
                ('disease_treatment', models.TextField(max_length=100)),
                ('age_diagnosed', models.PositiveIntegerField()),
                ('lab_results', models.TextField(max_length=100)),
                ('recurrency', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
